### PR TITLE
Tests: also include the crypto_kem directory

### PR DESCRIPTION
**Pull request by vbgl**
Do not merge before https://github.com/jasmin-lang/jasmin/issues/250 is fixed and https://github.com/jasmin-lang/jasmin/pull/249 is merged.

### CODE REVIEW

**Comment by vbgl** [comment]
When is the jasmin version updated in the CI machine? I believed that CI should be green by now.

**Comment by tfaoliveira** [comment]
> When is the jasmin version updated in the CI machine? I believed that CI should be green by now.

Hi @vbgl, the update should happen soon, I'm still catching up, but I think I should use https://github.com/jasmin-lang/jasmin/releases/tag/v2022.09.0

**Comment by vbgl** [comment]
Best if you can test against released versions (aka 2022.09.0) and development versions (aka `main`).

**Comment by tfaoliveira** [comment]
> Best if you can test against released versions (aka 2022.09.0) and development versions (aka `main`).

OK. Should I consider each commit in Jasmin main? Or once per day would be fine?

**Comment by tfaoliveira** [comment]
I see that [build-from-tarball](https://github.com/jasmin-lang/jasmin/blob/e2467f33b24b673bda35c2cca2ae3b7702c42ced/.gitlab-ci.yml#L161) is quite fast, so, for each commit then

**Pull request merged**
