### PR TITLE
libjade: update license: CC0-1.0 OR Apache-2.0

### PR DESCRIPTION
**Pull request by tfaoliveira**
This PR updates libjade to a dual license (previously CC0, now CC0 and Apache).

Motivation: allow libjade to be integrated by other libraries, for instance, https://github.com/open-quantum-safe/liboqs/pull/1745

Note: I plan to propagate these changes to all branches in libjade. 

I will request a review from libjade contributors so they can acknowledge this license update: 
* I can assign up to 15 reviewers to this PR; these will be the first 15 from `git shortlog -sne --all`
* The remaining will be tagged in a comment, and they can react with a +1 if they are OK with the license change

### CODE REVIEW

**Comment by tfaoliveira** [comment]
@ruipedro16 
@praveksharma
@loutr
@claucece

**Review by Rixxc — APPROVED** [review]

**Review by mbbarbosa — APPROVED** [review]

**Review by bacelar — APPROVED** [review]

**Review by vincentvbh — APPROVED** [review]

**Review by MQuaresma — APPROVED** [review]

**Review by basavesh — APPROVED** [review]

**Review by eponier — APPROVED** [review]
My only contribution to libjade is updating a hash, so I do not think you need my approval, but here it is anyway.

**Comment by vbgl** [comment]
Can someone please elaborate how the current CC0 license forbids to distribute libjade under the Apache license?

**Comment by vincentvbh** [comment]
https://github.com/open-quantum-safe/liboqs/issues/1388

**Review by vbgl — APPROVED** [review]

**Review by JoaoDiogoDuarte — APPROVED** [review]

**Review by fdupress — APPROVED** [review]

**Review by potsrevennil — APPROVED** [review]

**Review by dsprenkels — APPROVED** [review]
LGTM

**Review by sarranz — APPROVED** [review]

**Pull request merged**
